### ISSUE TITLE
ValueError: Unknown layer: Functional

### ISSUE THREAD

**Issue by Ykram12** [Zhang-VISLab/Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space#16]
Currently running this in Windows with conda (the version of tensorflow-gpu ended up being 2.1.0, latest supported package version with conda at this moment)

While following the instructions in the README I found myself with this error when trying to run S3_network_testing.py with the the prepared dataset and pretrained model:

`
Error:
Traceback (most recent call last):
  File "S3_network_testing.py", line 37, in <module>
    model = tf.keras.models.load_model(model_path,custom_objects={'iou':fun.iou})
  File "C:\Users\eriver08\Miniconda3\envs\XYZNet\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "C:\Users\eriver08\Miniconda3\envs\XYZNet\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "C:\Users\eriver08\Miniconda3\envs\XYZNet\lib\site-packages\tensorflow_core\python\keras\saving\model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\eriver08\Miniconda3\envs\XYZNet\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "C:\Users\eriver08\Miniconda3\envs\XYZNet\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "C:\Users\eriver08\Miniconda3\envs\XYZNet\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 250, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Functional
`

I managed to fix it by modifying lines in:

S3_network_testing.py
   - Line 37: wrap fun.iou in a list

`
model = tf.keras.models.load_model(model_path,custom_objects={'iou':[fun.iou]})
`

My guess is that it could be a tensorflow version issue within the conda environment (some version supports the function as it is and another one requires it to be in a list). 

Also I noticed that there was another problem in the training script that wouldn't let me train the model from scratch:

S2_network_training.py
   - Line 83: wrap fun.iou in a list
`
model.compile(opti,loss ='categorical_crossentropy',metrics=[fun.iou])
`
   - Line 87: Comment this line (ShapeNet_model_16.h5 is a different version that was being trained locally?)
   - Line 88: Uncomment this line (actual name of the pretrained model is defined in saved_path)

I am guessing this last problem was just some code changes that were not supposed to be pushed to master.

**Comment by YechengLyu** [comment]
fun.iou is located at fun_network.py Line19 - 43. It seems that you failed to load this customized from a saved model. I guess it is due to your windows version of Tensorflow. 

I would suggest you to try on a Ubuntu version. An alternative solution would be dragging the iou function to S2_network_training.py, defining the network directly and try to load weight instead of loading the model.

Good luck!

Yecheng

**Comment by Ykram12** [comment]
Thanks but actually the "issue" I added was more of a documentation for people trying to implement this using the given steps in Windows since I did get it working (I mention that before referencing modifications) and it did work with the pre-trained model. Very nice work btw!

**Comment by Zhang-VISLab** [comment]
Hi Ykram12,

Thanks for trying our approach and letting us know about this issue! Please do let us know if there are more issues in the future. Thanks.
